9
2022-05-14 03:53:03.850565: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-14 03:53:03.850814: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Task is classification, not lift the flap.
Hard mining set to:both
Using materials: ['main_xml_viewpoint_2', 'main_xml_viewpoint_3', 'main_xml_viewpoint_4']
Hotswapped material loader being used.
{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11, 13: 12}
-------------------------------
Annotation Counts
-------------------------------
table                     10252
sofa                       3102
chair                     17117
window                     5089
bookshelf                  3324
bed                        2831
monitor                    2408
trash_bin                  2857
file_cabinet               1418
desk                       4200
lamp                        589
bathtub                    1518
flowerpot                   162
Total                     54867
-------------------------------

annotations: ../openrooms/annotation_files/train_main_viewpoints_0_1_v3.json
batch_size: 15
checkpoint: null
git: e22ff54d4e15e859ff3672c5fc808cec0abfc80d
imagedir: ../
imbalance_reweighting: false
learning_rate: 1.0e-05
num_classes: 13
num_decoder_heads: 8
num_decoder_layers: 6
test_annotations: null
test_imagedir: null
uncertainty_gate_type: learned
uncertainty_threshold: 0.8
weighted_prediction: false

No checkpoint was passed.
Starting epoch: 1
batch num:0
overall: tensor(6.8610, device='cuda:0', grad_fn=<AddBackward0>)
Traceback (most recent call last):
  File "train_hotswapped_viewpoint.py", line 176, in <module>
    for i, (context_images, target_images, context_images_2, target_images_2, bbox, labels_cpu) in enumerate(dataloader):
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/spandan/contextual_domain_adaptation/WhenPigsFlyContext/core/dataset_hotswapped_viewpoint.py", line 121, in __getitem__
    image_path_2 = os.path.join(chosen_material_fol_path, random.choice(chosen_mat_fol_images))
  File "/n/home05/smadan/.conda/envs/domain_adaptation/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
